/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconsClose: typeof import('~icons/icons/close')['default']
    IconsDownload: typeof import('~icons/icons/download')['default']
    IconsMenu: typeof import('~icons/icons/menu')['default']
    IconsNotification: typeof import('~icons/icons/notification')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
